baseURL: https://blog.andreatitolo.com
title: Andrea Titolo
languageCode: en-us
theme: hugo-theme-hello-friend-ng
PygmentsCodeFences: yes
PygmentsStyle: monokai
paginate: 10
rssLimit: 10
copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License.
archetypeDir: archetypes
contentDir: content
dataDir: data
layoutDir: layouts
publishDir: public
buildDrafts: no
buildFuture: no
buildExpired: no
canonifyURLs: yes
enableRobotsTXT: yes
enableGitInfo: no
enableEmoji: yes
enableMissingTranslationPlaceholders: no
disableRSS: no
disableSitemap: no
disable404: no
disableHugoGeneratorInject: no
permalinks:
  posts: /posts/:year/:month/:title/
author:
  name: Andrea Titolo
blackfriday:
  hrefTargetBlank: yes
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  goatCounter: "blog-andreatitolo"
  customCSS: []
  customJS: []
  dateform: Jan 2, 2006
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04
  dateformShort: Jan 2
  description: Personal blog, just a place to share experiences, ideas and such.
  disableReadOtherPosts: no
  enableGlobalLanguageMenu: no
  enableSharingButtons: yes
  enableThemeToggle: yes
  favicon:
    color:
      mask: '#1b1c1d'
      msapplication: '#1b1c1d'
      theme: '#1b1c1d'
  footer:
    author: yes
    bottomText:
      - Powered by <a href="http://gohugo.io">Hugo</a> and <a href=https://github.com/rhazdon/hugo-theme-hello-friend-ng>Hello Friend NG</a>
    copyright: yes
    rss: no
    topText: []
    trademark: yes
  homeSubtitle: Rambling about stuff
  images: ''
  justifyContent: yes
  keywords: ''
  logo:
    logoHomeLink: /
    logoMark: '~'
    logoText: $ cd /home/
  social:
    - name: twitter
      url: https://twitter.com/whysofurious1
    - name: mastodon
      url: https://mastodon.uno/@whysofurious
    - name: pixelfed
      url: https://pixelfed.uno/whysofurious
    - name: github
      url: https://github.com/andreatitolo
    - name: email
      url: mailto:titoloandrea@ik.me

languages:
  en:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
      rel="noopener">CC BY-NC 4.0</a>
    subtitle: Personal Blog
    weight: 1
  fr:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
      rel="noopener">CC BY-NC 4.0</a>
    subtitle: Personal Blog
    weight: 2
menu:
  main:
    - identifier: about
      name: About/
      url: about/
    - identifier: posts
      name: Posts/
      url: posts/
    - identifier: snowflake
      name: Snowflake/
      url: snowflake/
  
markup:
  goldmark:
    renderer:
      unsafe: true
